name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter with FVM
        run: |
          curl -fsSL https://fvm.app/install.sh | bash
          export PATH="$HOME/.pub-cache/bin:$PATH"
          fvm install
          fvm use

      - name: Install dependencies
        run: fvm flutter pub get

      - name: Activate Spider
        run: fvm dart pub global activate spider

      - name: Run Code Generation
        run: |
          fvm flutter pub run build_runner build --delete-conflicting-outputs
          fvm dart pub global run spider build

      - name: Build Flutter Web
        run: fvm flutter build web --release --wasm --no-tree-shake-icons --base-href="/myprofile/"

      - name: Add .nojekyll and 404.html
        run: |
          touch build/web/.nojekyll
          echo '<!DOCTYPE html><html lang="en"><head><meta http-equiv="refresh" content="0; url=/" /></head><body></body></html>' > build/web/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
